### ISSUE TITLE
sun6i-a31s-bananapi-m2-plus.dts missing

### ISSUE THREAD

**Issue by ThomasKaiser** [BPI-SINOVOIP/BPI-Kernel4.0#1]
Can you please include the necessary hardware files that are still missing for your boards?

**Comment by BPI-SINOVOIP** [comment]
Dear Sir

We'll update the latest relevant source code of Banana Pi M2 to BPI Github as soon as possible.

In addition, it will be our pleasure to have the end users to maintain the code as well.

If you have any other new ideas, you may as well push your code here (https://github.com/BPI-SINOVOIP)

**Comment by ThomasKaiser** [comment]
We don't need forked source code! We need informations regarding the hardware. :-)

As soon as you publish the dts file here and the fex file used for the kernel 3.3 based images you provide and that's still missing from https://github.com/BPI-SINOVOIP/sunxi-boards/tree/master/sys_config/a31s/  the community can jump in. And instead of maintaining separate github ressources the best way to get support for the M2 would be to send patches to the linux-sunxi list https://groups.google.com/forum/#!forum/linux-sunxi to get the M2 supported upstream.

**Comment by ThomasKaiser** [comment]
Another week went by and you still fail to provide the dts file. Unbelievable.

**Comment by huyg** [comment]
@ThomasKaiser  
Hi, I have communicated whith BPI guys , For some complex reasons, the M2 kernel souce codes will have a delay release. I almost inquiry them everyday

**Comment by ThomasKaiser** [comment]
Thx for the answer. It's perfectly ok to wait a few weeks/months for some kernel sources as long as BPI-SINOVOIP publishes the missing pieces that are necessary to describe the M2 hardware correctly (especially pin mappings between SoC and outside) immediately. We need the .dts they use for mainline and the fex they use for kernel 3.3. Now.

**Comment by huyg** [comment]
SINOVOIP  has released the android 4.4 source codes for banana pi M2, include kernel 3.3

**Comment by ThomasKaiser** [comment]
And where do they released this stuff? This repo is empty https://github.com/BPI-SINOVOIP/BPI-M2-Android4.4 (same for Android 4.2) and they didn't release anything else.

**Comment by huyg** [comment]
http://pan.baidu.com/share/link?shareid=1715289951&uk=503403236
full android 4.4 source codes, 11.5GB, wish you have a high speed network to china

**Comment by ThomasKaiser** [comment]
Thx a lot! I just tried it and got ~240 bytes per second. Will take ages. And since the only thing of interest inside the package would be the fex file used to build u-boot and in the meantime Sergey Shatunov did some reverse engineering and provided the necessary and fixed .dts for mainline kernel -- http://pastebin.com/snznTi9H (if Sinovoip would use this Wi-Fi would work with their kernel 4.0 images) -- there's no need for the Android sources any longer :-)

**Comment by huyg** [comment]
fex at http://pastebin.com/MCA9PkXq , 
I tested the dts you supply , wifi works well, but power off can not shutdown the board power

**Comment by ThomasKaiser** [comment]
Thx, just had a look into it. It's a rather default fex from the SDK it seems (for example: 0 GPIO pin mappings defined --> no way to access GPIO stuff with the M2. And in case CSI/LVDS parameters are also just copy&paste then this might apply to camera/displays as well?).

Regarding power button: Did you try out these patches: http://lists.infradead.org/pipermail/linux-arm-kernel/2015-June/352213.html ?

**Comment by huyg** [comment]
I still not tried the PMIC patch, did you tried that ? 
By the way , who made the dtb? Can you put the dts source code to somewhere ? It must be very smaller than the dts dumped by fdtdump.

**Comment by ThomasKaiser** [comment]
I donated my M2 to the linux-sunxi community so there's no hardware to play with. Regarding .dts source: We/you have to wait for Prototik: http://www.bananapi.com/index.php/forum/general-discussion-for-bpi-m2/995-working-wifi-on-modern-kernels-4-1-tested

**Comment by BPI-SINOVOIP** [comment]
HI Thomas:
We're so excited and inspired to see this great achievement of yours, and I hope there are more opportunities for both of us to exchange experiences.
BPI has started to maintain kernel4.1.X (https://github.com/BPI-SINOVOIP/BPI-Kernel4.1.X), but there's still a lack of sun6i-a31s-bananapi-m2-plus.dts. Could you please give us some advice?
